server:
  port: 7000
spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_ADDRESS}:5432/postgres?schema=notification_service
    address: ${POSTGRES_ADDRESS}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    redis:
      database: 0
      host: ${REDIS_URL}
      port: 6379
      timeout: 120
  kafka:
    bootstrap-servers: localhost:39092, localhost:29092, localhost:19092
notification-service:
  ntfy:
    url: 'https://ntfy.sh/'
    topic: 'exemplo_aeiou'
  push:
    url: 'www.google.com.br'
  cache:
    ttl: 2
  kafka:
    topic: notification-consumer
    group-id: notification-service
    partition-number: 2
    replication-factor: 3