spring:
  r2dbc:
    url: "r2dbc:pool:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 120