server:
  port: 8086
spring:
  r2dbc:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      database: 0
      host: ${REDIS_HOST_URL}
      port: 6379
      timeout: 120