server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_ADDRESS}:5432/postgres
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  data:
    redis:
      database: 0
      host: ${REDIS_URL}
      port: 6379
      timeout: 120

notification-service:
  ntfy:
    url: 'ntfy.sh/'
    topic: 'exampleaeiou'
  push:
    url: 'www.google.com.br'